export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS= "SET_INGREDIENTS";
export const SET_INGREDIENTS_FAILED= "SET_INGREDIENTS_FAILED";

export const PURCHASE_START = "PURCHASE_START";
export const BURGER_SUCCESS = "BURGER_SUCCESS";
export const BURGER_FAIL = "BURGER_FAIL";