export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS= "SET_INGREDIENTS";
export const SET_INGREDIENTS_FAILED= "SET_INGREDIENTS_FAILED";

export const PURCHASE_START = "PURCHASE_START";
export const BURGER_SUCCESS = "BURGER_SUCCESS";
export const BURGER_FAIL = "BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REDIRECT = "AUTH_REDIRECT";